sudo: required
dist: precise
group: deprecated-2017Q1
language: perl
matrix:
  fast_finish: true
env:
  - SH=bash

before_install: make before_install

install: make install

script:
  - echo "Whoami at script"
  - sudo whoami
  - true
